[debug] [2025-10-22T22:30:58.801Z] ----------------------------------------------------------------------
[debug] [2025-10-22T22:30:58.804Z] Command:       C:\nvm4w\nodejs\node.exe C:\nvm4w\nodejs\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2025-10-22T22:30:58.804Z] CLI Version:   14.20.0
[debug] [2025-10-22T22:30:58.804Z] Platform:      win32
[debug] [2025-10-22T22:30:58.804Z] Node Version:  v20.19.4
[debug] [2025-10-22T22:30:58.804Z] Time:          Wed Oct 22 2025 17:30:58 GMT-0500 (hora estándar de Perú)
[debug] [2025-10-22T22:30:58.804Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-10-22T22:30:58.806Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\Users\tjcri\Documents\GitHub\Ecommerce-Dressia\nextn

[debug] [2025-10-22T22:31:00.200Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2025-10-22T22:31:00.200Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2025-10-22T22:33:14.068Z] ExitPromptError: User force closed the prompt with SIGINT
    at Interface.sigint (C:\Users\tjcri\AppData\Local\nvm\v20.19.4\node_modules\firebase-tools\node_modules\@inquirer\core\dist\commonjs\lib\create-prompt.js:101:37)
    at Interface.emit (node:events:524:28)
    at Interface.emit (node:domain:489:12)
    at [_ttyWrite] [as _ttyWrite] (node:internal/readline/interface:1125:18)
    at ReadStream.onkeypress (node:internal/readline/interface:264:20)
    at ReadStream.emit (node:events:536:35)
    at ReadStream.emit (node:domain:489:12)
    at emitKeys (node:internal/readline/utils:371:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:internal/readline/emitKeypressEvents:64:36)
[error] 
[error] Error: An unexpected error has occurred.
